version: "3"
services:
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=movies
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=settings.prod
    volumes:
      - .:/src
    command:
      /bin/bash -c "pip install -r requirements.txt; invoke run"
    links:
      - db
    ports:
      - 80:8000
volumes:
  pgdata: