version: "3"
services:
  web:
    build: .
    networks:
      - default
    env_file:
      - .env
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
    command:
      /bin/bash -c "pip install -r requirements.txt; invoke run"
    expose:
      - 8000
  nginx:
    image: nginx
    links:
      - web
    expose:
      - 80
    networks:
      - default
      - nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
      - ./media:/media:ro
    environment:
      - VIRTUAL_HOST=movies.ogir-ok.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=movies.ogir-ok.com
      - LETSENCRYPT_EMAIL=admin@movies.ogir-ok.com
networks:
  nginx-proxy:
    external: true
  default: