version: 2.1

jobs:
  deploy-prod:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "update apt"
          command: "sudo apt-get update"
      - run:
          name: "Install python3-pip"
          command: "sudo apt-get install python3-pip"

      - run:
          name: "install deploy requirements"
          command: "pip3 install pexpect boto3"

      - add_ssh_keys:
          fingerprints:
            - "a3:01:61:be:1b:58:f0:85:e8:e7:ed:fd:a6:d4:2d:7e"
      - run:
          name: "start deploy"
          command: "python3 daploy.py"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-prod:
    jobs:
      - deploy-prod
