version: 2.1

jobs:
  flake8:
    docker:
      - image: alpine/flake8
    steps:
      - checkout
      - run:
          name: "Flake8 check"
          command: "flake8"
  deploy-prod:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "update apt"
          command: "sudo apt-get update"
      - run:
          name: "Install python3-pip"
          command: "sudo apt-get install python3-pip"

      - run:
          name: "install deploy requierements"
          command: "pip3 install pexpect boto3"

      - add_ssh_keys:
          fingerprints:
            - "9e:f2:fe:9e:8e:c4:f9:10:df:fb:bc:d1:28:28:21:e0"

      - run:
          name: "start deploy"
          command: "python3 deploy.py"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-prod:
    jobs:
      - flake8
      - tests
      - deploy-prod
