# Generated by Django 3.2.8 on 2021-11-02 16:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=30, verbose_name='tconst')),
                ('title_type', models.CharField(choices=[(1, 'Kung Fury'), (2, 'Piper'), (3, 'presto')], max_length=100, verbose_name='titletype')),
                ('name', models.CharField(max_length=100, verbose_name='primaryTitle')),
                ('is_adult', models.BooleanField(max_length=5, verbose_name='IsAdult')),
                ('year', models.DateField(verbose_name='startYear')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='genres'), size=None), size=None)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.director')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=30, verbose_name='nconst')),
                ('name', models.CharField(max_length=100, verbose_name='primaryName')),
                ('birth_year', models.DateField(verbose_name='birthYear')),
                ('death_year', models.DateField(verbose_name='deathYear')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Ordering')),
                ('category', models.CharField(choices=[(1, 'Action'), (2, 'Horror'), (3, 'Comedy'), (4, 'Mystery')], max_length=30, verbose_name='Category')),
                ('job', models.CharField(choices=[(1, 'Director'), (2, 'Microphone Holder'), (3, 'Actor'), (4, 'Photographer')], max_length=30, verbose_name='Category')),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Characters'), size=None), size=None)),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.person')),
            ],
        ),
    ]
