# Generated by Django 3.2.8 on 2021-11-03 17:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255, verbose_name='')),
                ('title_type', models.CharField(choices=[], max_length=255, verbose_name='titleType')),
                ('name', models.CharField(max_length=255, verbose_name='primaryName')),
                ('is_adult', models.BooleanField(default=False, verbose_name='isAdult')),
                ('year', models.DateField(verbose_name='startYear')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255, verbose_name='')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('birth_year', models.DateField(max_length=255, verbose_name='birthYear')),
                ('death_year', models.DateField(max_length=255, verbose_name='deathYear')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=255, verbose_name='ordering')),
                ('category', models.CharField(choices=[], max_length=255, verbose_name='category')),
                ('job', models.CharField(choices=[], max_length=255, verbose_name='job')),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='characters'), size=None), size=None)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.person')),
            ],
        ),
    ]
