# Generated by Django 3.2.8 on 2021-11-18 08:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='imdb_id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='IsAdult'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_type',
            field=models.CharField(choices=[('short', 'Short'), ('movie', 'Movie')], default='short', max_length=80, verbose_name='Title_type'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(null=True, verbose_name='Release Year'),
        ),
    ]
