# Generated by Django 3.2.8 on 2021-11-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmovie',
            options={'ordering': ['-person_id']},
        ),
        migrations.AddField(
            model_name='movie',
            name='persons_participating',
            field=models.ManyToManyField(through='movies.PersonMovie', to='movies.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='movies_participating',
            field=models.ManyToManyField(through='movies.PersonMovie', to='movies.Movie'),
        ),
    ]
