# Generated by Django 3.2.8 on 2021-11-12 16:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='imdb id'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Is adult rated'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_type',
            field=models.CharField(choices=[('short', 'Short'), ('movie', 'Movie')], default='short', max_length=80, verbose_name='Title_type'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(null=True, verbose_name='Release year'),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
