# Generated by Django 3.2.8 on 2021-11-17 20:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='nconst')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='primaryName')),
                ('birth_year', models.DateField(blank=True, null=True, verbose_name='birthYear')),
                ('death_year', models.DateField(blank=True, null=True, verbose_name='deathYear')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='ordering')),
                ('category', models.CharField(blank=True, choices=[('AC-R', 'actor'), ('AC-S', 'actress'), ('CIN', 'cinematographer'), ('COM', 'composer'), ('DIR', 'director'), ('ED', 'editor'), ('PR', 'producer'), ('SEL', 'self'), ('WR', 'writer')], max_length=100, null=True, verbose_name='category')),
                ('job', models.CharField(blank=True, choices=[('CO-D', 'co-director'), ('COM', 'comic strip'), ('DIR-P', 'director of photography'), ('NOV', 'novel'), ('PL', 'play'), ('PO', 'poem'), ('PR', 'producer'), ('SC', 'scenario'), ('SC-P', 'screen play'), ('ST', 'story'), ('WR', 'writer')], max_length=100, null=True, verbose_name='job')),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='characters'), blank=True, null=True, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='imdb id'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Is Adult rated'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_type',
            field=models.CharField(choices=[('SH', 'short'), ('MOV', 'movie')], default='SH', max_length=80, null=True, verbose_name='Title_Type'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Release year'),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AddField(
            model_name='personmovie',
            name='movie_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='personmovie',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.person'),
        ),
    ]
