# Generated by Django 3.2.8 on 2021-11-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211104_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmovie',
            name='movie_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.person'),
        ),
    ]
