# Generated by Django 3.2.8 on 2021-11-17 22:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211117_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(null=True, verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.DateField(null=True, verbose_name='birthYear'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.DateField(null=True, verbose_name='deathYear'),
        ),
        migrations.AlterField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(max_length=10, null=True, verbose_name='nconst'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='primaryName'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='category',
            field=models.CharField(choices=[('AC-R', 'actor'), ('AC-S', 'actress'), ('CIN', 'cinematographer'), ('COM', 'composer'), ('DIR', 'director'), ('ED', 'editor'), ('PR', 'producer'), ('SEL', 'self'), ('WR', 'writer')], max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='characters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='characters'), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='job',
            field=models.CharField(choices=[('CO-D', 'co-director'), ('COM', 'comic strip'), ('DIR-P', 'director of photography'), ('NOV', 'novel'), ('PL', 'play'), ('PO', 'poem'), ('PR', 'producer'), ('SC', 'scenario'), ('SC-P', 'screen play'), ('ST', 'story'), ('WR', 'writer')], max_length=100, null=True, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='order',
            field=models.IntegerField(null=True, verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.person'),
        ),
    ]
